version: '3'

services:
  frontend-admin:
    build:
      context: ./Client/Admin
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    networks:
      - mynetwork
  
  frontend-user:
    build:
      context: ./Client/User
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    networks:
      - mynetwork

  backend:
    build:
      context: ./Server
      dockerfile: Dockerfile
    environment:
      - ATLAS_URI=mongodb+srv://dhanu:dhanu751@full-stack-development.nipgpqd.mongodb.net/?retryWrites=true&w=majority
      - JWT_SECRET=fc6b436fb79612607f5032a7455cc73c1ad1ff0a4ca1fddf2a0d4fa746d5c8f3
      - PORT=3000
    ports:
      - "3000:3000"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
