export const PaymentModel = {
    _id: String,
    transactionId: String,
    reservationId: {
        _id: String,
        userId: String,
        arrivalDate: String,
        arrivalTime: String,
        departureDate: String,
        departureTime: String,
        roomId: {
            _id: String,
            roomType: String,
            availability: Boolean,
            facilities: String,
            persons: Number,
            price: Number,
            image: String,
        },
        noOfRooms: Number,
        foodType: String,
        noOfAdults: Number,
        noOfChildren: Number,
        specialRequirements: String,
    },
    userId: {
        _id: String,
        fullName: String,
        userName: String,
        contactNumber: Number,
        address: String,
        nic: String,
        password: String,
    },
    amount: Number,
};
