name: Docker Compose CI

on:
  push:
    branches: ["dev"]

jobs:
  Build-and-Push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.18.0

      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: Install Dependecies in Admin
        run: |
          npm install
          npm ci
        working-directory: ./Client/Admin/

      - name: Build Admin
        run: npm run build
        working-directory: ./Client/Admin/

      - name: Save version Admin
        id: version-admin
        run: echo ::set-output name=tag::$(echo $(node -p -e "require('./package.json').version"))
        working-directory: ./Client/Admin/

      - name: Install Dependecies in User
        run: yarn
        working-directory: ./Client/User/

      - name: Build User
        run: yarn build
        working-directory: ./Client/User/

      - name: Save version User
        id: version-user
        run: echo ::set-output name=tag::$(echo $(node -p -e "require('./package.json').version"))
        working-directory: ./Client/User/

      - name: Install Dependecies in Chat
        run: yarn
        working-directory: ./Client/Chat/

      - name: Build Chat
        run: yarn build
        working-directory: ./Client/Chat/

      - name: Save version Chat
        id: version-chat
        run: echo ::set-output name=tag::$(echo $(node -p -e "require('./package.json').version"))
        working-directory: ./Client/Chat/

      - name: Install Dependecies in Server
        run: |
          npm install
          npm ci
        working-directory: ./Server/

      - name: Save version Server
        id: version-server
        run: echo ::set-output name=tag::$(echo $(node -p -e "require('./package.json').version"))
        working-directory: ./Server/

      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build and Push Docker Images
        run: |
          docker-compose build

          docker tag admin-image:local ${{ secrets.DOCKERHUB_USERNAME }}/frontend-admin:${{ steps.version-admin.outputs.tag }}
          docker tag user-image:local ${{ secrets.DOCKERHUB_USERNAME }}/frontend-user:${{ steps.version-user.outputs.tag }}
          docker tag chat-image:local ${{ secrets.DOCKERHUB_USERNAME }}/frontend-chat:${{ steps.version-chat.outputs.tag }}
          docker tag server-image:local ${{ secrets.DOCKERHUB_USERNAME }}/backend:${{ steps.version-server.outputs.tag }}

          docker push ${{ secrets.DOCKERHUB_USERNAME }}/frontend-admin:${{ steps.version-admin.outputs.tag }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/frontend-user:${{ steps.version-user.outputs.tag }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/frontend-chat:${{ steps.version-server.outputs.tag }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/backend:${{ steps.version-server.outputs.tag }}
