name: Docker Compose CI

on:
  push:
    branches: ["ravindu"]

jobs:
  Docker-Compose:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: Dependecies
        run: |
          npm install
          npm ci

      - name: Build
        run: npm run build

      - name: Save version
        id: version
        run: echo ::set-output name=tag::$(echo $(node -p -e "require('./package.json').version"))

      - name: Increase version
        run: npm version patch

      - name: Push new version
        run: git push --force

      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      
      - name: Build and Push Docker Images
        run: |
          docker-compose build

          # Tag and push frontend-admin service
          docker tag frontend-admin:latest ${{ secrets.DOCKERHUB_USERNAME }}/frontend-admin:${{ steps.version.outputs.tag }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/frontend-admin:${{ steps.version.outputs.tag }}

          # Tag and push frontend-user service
          docker tag frontend-user:latest ${{ secrets.DOCKERHUB_USERNAME }}/frontend-user:${{ steps.version.outputs.tag }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/frontend-user:${{ steps.version.outputs.tag }}

          # Tag and push backend service
          docker tag backend:latest ${{ secrets.DOCKERHUB_USERNAME }}/backend:${{ steps.version.outputs.tag }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/backend:${{ steps.version.outputs.tag }}
