name: Docker Compose CI

on:
  push:
    branches: ["ravindu"]

jobs:
  Build-and-Push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: change-dir-Admin
      - run: cd Client/Admin/
      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: Dependecies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Save version
        id: version-admin
        run: echo ::set-output name=tag::$(echo $(node -p -e "require('./package.json').version"))

      - name: Change directory - User
        run: cd ../User/

      - name: Dependecies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Save version
        id: version-user
        run: echo ::set-output name=tag::$(echo $(node -p -e "require('./package.json').version"))

      - name: change directory - Server
        run: cd ../../Server/

      - name: Dependecies
        run: npm ci

      - name: Save version
        id: version-server
        run: echo ::set-output name=tag::$(echo $(node -p -e "require('./package.json').version"))

      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: change directory - Root
        run: cd ..

      - name: Build and Push Docker Images
        run: |
          docker-compose build

          # Tag and push frontend-admin service
          docker tag frontend-admin:latest ${{ secrets.DOCKERHUB_USERNAME }}/frontend-admin:${{ steps.version-admin.outputs.tag }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/frontend-admin:${{ steps.version-admin.outputs.tag }}

          # Tag and push frontend-user service
          docker tag frontend-user:latest ${{ secrets.DOCKERHUB_USERNAME }}/frontend-user:${{ steps.version-user.outputs.tag }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/frontend-user:${{ steps.version-user.outputs.tag }}

          # Tag and push backend service
          docker tag backend:latest ${{ secrets.DOCKERHUB_USERNAME }}/backend:${{ steps.version-server.outputs.tag }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/backend:${{ steps.version-server.outputs.tag }}
