name: Run Tests - CI

on:
  push:
    branches: ["ravindu"]
  pull_request:
    branches: ["dev"]

jobs:
  Run-Testings-CI:
    defaults:
      run:
        working-directory: ./Client/Admin
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18.x"
      - name: Install dependencies
        run: |
          npm install
          npm ci
      - name: Run tests (Jest and Supertest)
        run: npm run test
