name: Run Tests - CI

on:
  push:
    branches: ["temp"]

jobs:
  Run-Tests-CI:
    defaults:
      run:
        working-directory: ./Server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: Dependecies
        run: |
          npm install --force
          npm ci
      - name: Run Tests - CI
        run: npm run test
